name: 'Utility'
description: 'Run any ozone runnable'
inputs:
  ozone_context:
    description: 'Ozone context'
    required: true
  ozone_version:
    description: 'Ozone version'
    required: true
  runnable_name:
    description: 'Runnable name.'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Install deps
      uses: ./.github/actions/install-build-deps
      with:
        ozone-version: ${{ inputs.ozone_version }}

    - name: "Ozone - Utiltiy."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone -d -c ${{ inputs.ozone_context }} run "${{ inputs.runnable_name }}"
      env:
        DOCKER_BUILDKIT: "1"

