// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package main

import (
	"database/sql"

	"google.golang.org/grpc"

	pb_counter "github.com/JamesArthurHolland/ivanti/profile-api/api/counter/v1"
	app_counter "github.com/JamesArthurHolland/ivanti/profile-api/internal/counter"
	"github.com/JamesArthurHolland/ivanti/profile-api/internal/server"
)

func registerServer(db *sql.DB) server.RegisterServer {
	return func(grpcServer *grpc.Server) {
		pb_counter.RegisterCounterServiceServer(grpcServer, app_counter.NewService(app_counter.New(db), db))

	}
}

func registerHandlers() []server.RegisterHandlerFromEndpoint {
	var handlers []server.RegisterHandlerFromEndpoint

	handlers = append(handlers, pb_counter.RegisterCounterServiceHandlerFromEndpoint)

	return handlers
}
