name: 'Tag with new version tag'
description: 'Retags a service with static version container tag, using the dynamic tag as the source.'
inputs:
  env:
    description: 'Environment name'
    required: true
  service_name:
    description: 'Service name.'
    required: true
  ozone_version:
    description: 'Ozone version'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Install deps
      uses: ./.github/actions/install-build-deps
      with:
        ozone-version: ${{ inputs.ozone_version }}
        kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

    - name: Get version
      id: version
      uses: ./.github/actions/get-version
      with:
        env: ${{ inputs.env }}

    - name: "Ozone - Retag."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone -d -c tagging run "tag-through-dynamic-to-static-${{ inputs.service_name}}"
      env:
        GIT_BRANCH: ${{ github.head_ref }}
        GITHUB_USERNAME: ${{ inputs.github_username }}
        DOCKER_REGISTRY: "${{ steps.login-ecr-dev.outputs.registry }}"
        LIVE_DOCKER_REGISTRY: "${{ steps.login-ecr-live.outputs.registry }}"
        DOCKER_BUILDKIT: "1"
        PRODUCT_OVERALL_VERSION: "${{ steps.version.outputs.semantic_version_from_git_branchname }}"
