name: 'Deploy'
description: 'Builds containers, pushes them to docker repo, tests with postman/newman'
inputs:
  domain:
    description: 'Domain'
    required: true
  env:
    description: 'Environment name'
    required: true
  ozone_context:
    description: 'Ozone context'
    required: true
  ozone_runnable:
    description: 'Ozone runnable'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies



    - name: "Ozone - Deploy."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone -d -c "${{ inputs.ozone_context }}" run "${{ inputs.ozone_runnable }}"
      env:
        DOMAIN: ${{ inputs.domain }}
        ENV: ${{ inputs.env }}
        CERT_DIR: ${{ inputs.cert_dir }}
        GIT_BRANCH: ${{ github.head_ref }}
        GITHUB_USERNAME: ${{ inputs.github_username }}
        DOCKER_REGISTRY: ozone2021
        DOCKER_BUILDKIT: "1"
        USES_CONTAINER_DB: ${{ inputs.uses_container_db }}
        DB_HOST: ${{ inputs.db_host }}

