name: 'Teardown'
description: 'Builds containers, pushes them to docker repo, tests with postman/newman'
inputs:
  env:
    description: 'Environment name'
    required: true
  ozone_context:
    description: 'Ozone context'
    required: true
  ozone_version:
    description: 'Ozone version'
    required: true
  lke_creds_base64:
    description: 'LKE creds base64'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Install deps
      uses: ./.github/actions/install-deploy-deps
      with:
        ozone-version: ${{ inputs.ozone_version }}
        kube_config: ${{ inputs.lke_creds_base64 }}

    - name: "Ozone - Teardown non-release."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone -d -c ${{ inputs.ozone_context }} run teardown
      env:
        GIT_BRANCH: ${{ github.head_ref }}
