// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc). DO NOT EDIT.

package counter

import (
	pb "github.com/JamesArthurHolland/ivanti/profile-api/api/counter/v1"
)

func toCounter(in Counter) *pb.Counter {

	out := new(pb.Counter)
	out.Id = in.ID.String()
	out.Count = in.Count
	return out
}
