// Code generated by sqlc-grpc (https://github.com/walterwanderley/sqlc-grpc).

package counter

import (
	"database/sql"

	pb "github.com/JamesArthurHolland/ivanti/profile-api/api/counter/v1"
)

// NewService is a constructor of a pb.CounterServiceServer implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries, db *sql.DB) pb.CounterServiceServer {
	return &Service{querier: querier}
}
