name: 'Build'
description: 'Builds containers'
inputs:
  ozone_context:
    description: 'Ozone context'
    required: true
  ozone_version:
    description: 'Ozone version'
    required: true
  env:
    description: 'Environment'
    required: true
  service_name:
    description: 'Service name.'
    required: true
  lke_creds:
    description: 'LKE creds'
    required: true
  docker_username:
    description: 'Docker username'
    required: true
  docker_password:
    description: 'Docker password'
    required: true
  docker_registry:
    description: 'Docker registry id'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Install deps
      uses: ./.github/actions/install-build-deps
      with:
        ozone-version: ${{ inputs.ozone_version }}
        kube_config: ${{ inputs.lke_creds }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: "Ozone - Build."
      shell: bash
      run: cd $GITHUB_WORKSPACE && ozone -d -c ${{ inputs.ozone_context }} run install-build-deploy-all
      env:
        GIT_BRANCH: ${{ github.head_ref }}
        DOCKER_BUILDKIT: "1"
        DOCKER_REGISTRY: ${{ inputs.docker_registry }}
