apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ivanti.{{ .Values.namespace }}.{{ .Values.domain }}
spec:
  hosts:
    - {{ .Values.services.api.host }}
  gateways:
    - istio-system/docker-registry-ivanti-gateway-{{ .Values.env }}
  http:
    - route:
        - destination:
            host: oneapi.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: 80