apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-virtual-service
spec:
  hosts:
    - {{ .Values.services.api.host }}
  gateways:
    - istio-system/docker-registry-ivanti-gateway
  http:
    - route:
        - destination:
            host: ivanti-live.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: 80