name: 'Install deps'
description: 'Installs Ozone, Infisical'
inputs:
  ozone-version:
    description: 'Ozone version'
    required: true

runs:
  using: "composite"
  steps:
    - uses: abbbi/github-actions-tune@v1

    - name: "Install infisical repo"
      shell: bash
      run: curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: "Install ozone."
      shell: bash
      run: go install github.com/ozone2021/ozone/ozone@${{ inputs.ozone-version }}

    - name: "Install infisical"
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y infisical
