name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      ozone_context:
        required: true
        type: string
      ozone_version:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      GH_PAT:
        required: true

jobs:
  build_api:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.39
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions/ozone_build
        with:
          ozone_context: ${{ inputs.ozone_context }}
          ozone_version: ${{ inputs.ozone_version }}
          service_name: api
          env: ${{ inputs.env }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          docker_registry: ivanti


