name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      ozone_context:
        required: true
        type: string
      ozone_version:
        required: true
        type: string
      github_username:
        required: true
        type: string


jobs:
  build_api:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/ozone_build
        with:
          ozone_context: ${{ inputs.ozone_context }}
          ozone_version: ${{ inputs.ozone_version }}
          service_name: api
          env: ${{ inputs.env }}


