name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      is_release_version:
        required: true
        type: boolean
      ozone_context:
        required: true
        type: string
      ozone_version:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build_api:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions/ozone_build
        with:
          ozone_context: ${{ inputs.ozone_context }}
          ozone_version: ${{ inputs.ozone_version }}
          service_name: api
          is_release_version: ${{ inputs.is_release_version }}
          env: ${{ inputs.env }}


