name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      deployment_secret:
        description: 'Deployment secret'
        required: true
jobs:
  deploy_all:
    name: Deploy all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: Get version
        id: version
        uses: ./.github/actions/get-version
        with:
          env: production

      - name: "Deploy to production"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run deploy-prod
        env:
          DOCKER_REGISTRY: ozone2021
          GIT_BRANCH: ${{ github.head_ref }}
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN_BUILD_LIVE }}
          PRODUCT_OVERALL_VERSION: ${{ steps.version.outputs.semantic_version_from_git_tag }} # wrong I think?
