name: FEATURE Pull Request Opened / Committed to
on:
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_all:
    name: Build all
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      ozone_context: pull-request
      env: "pr"
      is_release_version: false
      ozone_version: 1.4.33

  deploy_all:
    name: Deploy all
    needs:
      - build_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

#      - uses: ./.github/workflows/build.yml
#        with:
#          ozone_context: pull-request
#          env: "pr"
#          is_release_version: false
#          ozone_version: 1.4.33

      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: "Ozone - Deploy Feature PR"
        shell: bash
        run: export GIT_BRANCH=$(./script/utils/dynamic_namespace.sh) && export GIT_BRANCH="ozone2021/api:$GIT_BRANCH" && cd "$GITHUB_WORKSPACE" && ozone -d -c pull-request run deploy-pr
        env:
          DOCKER_REGISTRY: ozone2021
#          GIT_BRANCH: ${{ github.head_ref }}
          DOMAIN: "ivanti.com"

  tests:
    name: Postman e2e Tests
    needs:
      - deploy_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-e2e-test-deps
        with:
          ozone-version: 1.4.33

      - name: "Ozone - Postman tests"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c pull-request run postman-tests
        env:
          GIT_BRANCH: ${{ github.head_ref }}