name: Live
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_all:
    name: Build all
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
      LKE_CREDS_BASE64: ${{ secrets.LKE_CREDS_BASE64 }}
    with:
      ozone_context: live
      env: "live"
      ozone_version: 1.4.39

  deploy_all:
    name: Deploy all
    needs:
      - build_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.39
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Deploy"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run deploy-prod
        env:
          DOCKER_REGISTRY: ivanti
          GIT_BRANCH: ${{ github.head_ref }}
          ENV: "live"

      - name: "Ozone - Postman tests"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run postman-tests
        env:
          GIT_BRANCH: ${{ github.head_ref }}

  tests:
    name: Postman e2e Tests
    needs:
      - deploy_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-e2e-test-deps
        with:
          ozone-version: 1.4.39

      - name: "Ozone - Postman tests"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run postman-tests
        env:
          GIT_BRANCH: ${{ github.head_ref }}