name: STAGING
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_all:
    name: Build all
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      ozone_context: pull-request
      env: "pr"
      ozone_version: 1.4.36

  deploy_all:
    name: Deploy all
    needs:
      - build_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0

#      - uses: ./.github/workflows/build.yml
#        with:
#          ozone_context: live
#          env: "pr"
#          ozone_version: 1.4.36

      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.36
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: version
        uses: ./.github/actions/get-version
        with:
          ozone-version: 1.2.34
      - name: "Ozone - Postman tests"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run postman-tests
        env:
          GIT_BRANCH: ${{ github.head_ref }}

      - name: "Deploy"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run deploy-prod
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_BRANCH: ${{ github.head_ref }}
