name: STAGING
on:
  push:
    branches:
      - main

jobs:
  deploy_all:
    name: Deploy all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      build_all:
        name: Build all
        uses: ./.github/workflows/build.yml
        secrets:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          OZONE_CONTEXT: pull-request
          ENV: "pr"
          IS_RELEASE_VERSION: false
          OZONE_VERSION: 1.4.33

      deploy_all:
        name: Deploy all
        needs:
          - build_all
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              submodules: recursive
              fetch-depth: 0

