name: STAGING
on:
  push:
    branches:
      - main

jobs:
  deploy_all:
    name: Deploy all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: version
        uses: ./.github/actions/get-version
        with:
          env: staging

      - name: "Deploy to live"
        shell: bash
        run: cd $GITHUB_WORKSPACE && ozone -d -c live run build-all deploy-prod
        env:
          GIT_BRANCH: ${{ github.head_ref }}
          PRODUCT_OVERALL_VERSION: "1.0"
          ENV: live
          DOMAIN: "ivanti.com"

