name: STAGING
on:
  push:
    branches:
      - main

jobs:
  deploy_all:
    name: Deploy all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33

      - name: Get version
        id: version
        uses: ./.github/actions/get-version
        with:
          env: staging

      - name: "Deploy to staging"
        shell: bash
        run: cd $GITHUB_WORKSPACE && infisical run --env=staging --path=/ -- ozone -d -c live run deploy-staging
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_BRANCH: ${{ github.head_ref }}
          PRODUCT_OVERALL_VERSION: ${{ steps.version.outputs.semantic_version_from_git_tag }} # wrong I think?
