name: RELEASE Pull Request Opened / Committed to
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  build_all:
    name: Build all
    uses: ./.github/workflows/build.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      GH_PAT: ${{ secrets.GH_PAT }}
    with:
      ozone_context: release-pr
      docker_registry_id: 624086393560
      env: "pr"
      is_release_version: false # change to is_semantic_versioned_release
      github_username: vessul-cicd
      ozone_version: 1.4.33

  deploy_all:
    name: Deploy all
    needs:
      - build_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install deps
        uses: ./.github/actions/install-deploy-deps
        with:
          ozone-version: 1.4.33
          kube_config: ${{ secrets.LKE_CREDS_BASE64 }}
      - uses: ./.github/actions/ozone_deploy
        with:
          cert_dir: "ingressgateway-certs"
          domain: "pr.vessul.atpi.com"
          env: "dev"
          is_release_version: false
          ozone_context: release-pr
          ozone_runnable: deploy-pr
          uses_container_db: false
