name: Retag
on:
  workflow_call:
    inputs:
      deployment_prefix:
        required: false
        type: string
      docker_registry_id:
        required: true
        type: string
      live_docker_registry_id:
        required: true
        type: string
      env:
        required: true
        type: string
      ozone_version:
        required: true
        type: string
    secrets:
      GH_PAT:
        description: "Github pattern access token"
        required: true
      DEV_AWS_ACCESS_KEY_ID:
        description: "AWS credential"
        required: true
      DEV_AWS_SECRET_ACCESS_KEY:
        description: "AWS credential"
        required: true
      LIVE_AWS_ACCESS_KEY_ID:
        description: "AWS credential"
        required: true
      LIVE_AWS_SECRET_ACCESS_KEY:
        description: "AWS credential"
        required: true

jobs:
  #  retag_database:
  #    name: Retag database
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #        with:
  #          submodules: recursive
  #          token: ${{ secrets.GH_PAT }}
  #          fetch-depth: 0
  #      - uses: ./.github/actions/ozone_new_version_tags
  #        with:
  #          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  #          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  #          ozone_context: pull-request
  #          docker_registry_id: ${{ inputs.docker_registry_id }}
  #          deployment_prefix: ${{ inputs.deployment_prefix }}
  #          service_name: database
  #          gh_pat: ${{ secrets.GH_PAT }}

  retag_api:
    name: Retag api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: api
          env: ${{ inputs.env }}

  retag_booking:
    name: Retag booking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: booking
          env: ${{ inputs.env }}

  retag_card:
    name: Retag card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: card
          env: ${{ inputs.env }}

  retag_eprofile:
    name: Retag eprofile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: eprofile
          env: ${{ inputs.env }}

  retag_frogpoint:
    name: Retag frogpoint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: frogpoint
          env: ${{ inputs.env }}

  retag_crewchange:
    name: Retag crewchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: crewchange
          env: ${{ inputs.env }}

  retag_migrator:
    name: Retag migrator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: migrator
          env: ${{ inputs.env }}

  retag_ticketwindow:
    name: Retag ticketwindow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: ticketwindow
          env: ${{ inputs.env }}

  retag_trip:
    name: Retag trip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: trip
          env: ${{ inputs.env }}

  retag_ui:
    name: Retag ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: ui
          env: ${{ inputs.env }}

  retag_locationsearch:
    name: Retag locationsearch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: locationsearch
          env: ${{ inputs.env }}

  retag_locationbatch:
    name: Retag locationbatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: locationbatch
          env: ${{ inputs.env }}

  retag_taptrip_elastic:
    name: Retag taptrip elastic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - uses: ./.github/actions/ozone_new_version_tags
        with:
          aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          live_aws_access_key_id: ${{ secrets.LIVE_AWS_ACCESS_KEY_ID }}
          live_aws_secret_access_key: ${{ secrets.LIVE_AWS_SECRET_ACCESS_KEY }}
          ozone_version: ${{ inputs.ozone_version }}
          docker_registry_id: ${{ inputs.docker_registry_id }}
          live_docker_registry_id: ${{ inputs.live_docker_registry_id }}
          service_name: taptrip_elastic
          env: ${{ inputs.env }}