name: Build
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  tag:
    name: Tag container with semantic version.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Get version
        id: version
        uses: ./.github/actions/get-version
        with:
          env: ${{ inputs.env }}

      - run: git config --global user.email "githubactions@ozone.com"
        shell: bash

      - run: git config --global user.name "github actions"
        shell: bash

      - name: "Git tag commit hash"
        if: inputs.env == 'dev'
        shell: bash
        run: if [ ! $(git tag -l "$VERSION") ]; then git tag -a "$VERSION" -m "$(date) $VERSION" && git push --tags; fi
        env:
          VERSION: ${{ steps.version.outputs.semantic_version_from_git_branchname }}