name: Release Pull Request Closed/Merged
on:
  pull_request:
    types: [closed]
    branches:
      - 'develop'

jobs:
  merge_pr:
    name: Pull request merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/ozone_teardown
        with:
          env: "pr"
          ozone_context: release-pr
          ozone_version: 1.4.33
