name: Feature Pull Request Closed/Merged
on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

jobs:
  merge_pr:
    name: Pull request merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/ozone_teardown
        with:
          env: "pr"
          ozone_context: pull-request
          ozone_version: 1.4.36
